ALTER TABLE ebay_traffic_sync
  ADD COLUMN IF NOT EXISTS today_day DATE,
  ADD COLUMN IF NOT EXISTS today_fetched_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS refresh_day DATE,
  ADD COLUMN IF NOT EXISTS refresh_count INTEGER NOT NULL DEFAULT 0;
